### PR TITLE
Bug 1129445 - Breaking up memory logging into separate entries

### PR DESCRIPTION
**Pull request by eliperelman**

### CODE REVIEW

**Comment by rwood-moz** [comment]
This is timing out after writing the performance entries (tested on flame-kk device):

rwood@ubuntu:~/gaia$ DEBUG=\* APPS='clock' RUNS=1 node tests/raptor/launch_test.js 
  mozdevice:command [Executing] adb devices +0ms
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb shell 'getprop' +8ms
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb push /home/rwood/node-mozdevice/orng /data/local/orng +78ms
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb shell 'chmod 777 /data/local/orng' +147ms
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb pull /system/b2g/webapps/settings.gaiamobile.org/application.zip /tmp/raptor-temp11529-7531-yvg8dm/application.zip +61ms
  mozdevice:util Gaia revision for device: fd2a4d10dc156614d417a432f5ec5f93966bbb1b +3s
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb pull /system/sources.xml /tmp/raptor-temp11529-7531-xm5yrw/sources.xml +2ms
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb pull /system/b2g/application.ini /tmp/raptor-temp11529-7531-sdsb2k/application.ini +220ms
  mozdevice:util Gecko revision for device: eab4a81e4457 +180ms
  mozdevice:logging Clearing +7ms
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb shell 'logcat -c' +1ms
  mozdevice:util Restarting B2G +74ms
  mozdevice:command [Executing] DEVICETIME=$(ANDROID_SERIAL=3739cec3 adb shell echo '$EPOCHREALTIME') && ANDROID_SERIAL=3739cec3 adb shell 'stop b2g && start b2g' && echo $DEVICETIME +0ms
  raptor:coldlaunch Waiting for homescreen +0ms
  raptor:coldlaunch Received performance entry `loadEnd` in system.gaiamobile.org +11s
  raptor:coldlaunch Received performance entry `homescreenStart` in system.gaiamobile.org +13s
  raptor:coldlaunch Received performance entry `navigationLoaded` in verticalhome.gaiamobile.org +463ms
  raptor:coldlaunch Received performance entry `navigationInteractive` in verticalhome.gaiamobile.org +5ms
  raptor:coldlaunch Received performance entry `osLogoEnd` in system.gaiamobile.org +2s
  raptor:coldlaunch Received performance entry `visuallyLoaded` in verticalhome.gaiamobile.org +3ms
  raptor:coldlaunch Received performance entry `contentInteractive` in verticalhome.gaiamobile.org +4ms
  raptor:coldlaunch Received performance entry `fullyLoaded` in verticalhome.gaiamobile.org +625ms
  raptor:coldlaunch Capturing Homescreen PID: 1912 +0ms
  raptor:coldlaunch Priming Clock cold-launch +0ms
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb shell 'echo "drag 240 250 240 350 10 130" > /data/local/tmp/orng-cmd' +33s
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb shell '/data/local/orng /dev/input/event0 /data/local/tmp/orng-cmd' +315ms
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb shell 'echo "tap 300 213 1 1" > /data/local/tmp/orng-cmd' +3s
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb shell '/data/local/orng /dev/input/event0 /data/local/tmp/orng-cmd' +308ms
  raptor:coldlaunch Received performance entry `appLaunch` in clock.gaiamobile.org +10s
  raptor:coldlaunch Received performance entry `navigationLoaded` in clock.gaiamobile.org +1s
  raptor:coldlaunch Capturing application PID: 2040 +0ms
  raptor:coldlaunch Received performance entry `navigationInteractive` in clock.gaiamobile.org +117ms
  raptor:coldlaunch Received performance entry `visuallyLoaded` in clock.gaiamobile.org +354ms
  raptor:coldlaunch Received performance entry `contentInteractive` in clock.gaiamobile.org +2ms
  raptor:coldlaunch Received performance entry `fullyLoaded` in clock.gaiamobile.org +4ms
  mozdevice:util Killing process 2040 +2s
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb shell 'kill 2040' +0ms
[Test] Starting run 1
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb shell 'echo "tap 300 213 1 1" > /data/local/tmp/orng-cmd' +6s
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb shell '/data/local/orng /dev/input/event0 /data/local/tmp/orng-cmd' +309ms
  raptor:coldlaunch Received performance entry `appLaunch` in clock.gaiamobile.org +6s
  raptor:coldlaunch Received performance entry `navigationLoaded` in clock.gaiamobile.org +940ms
  raptor:coldlaunch Capturing application PID: 2090 +0ms
  raptor:coldlaunch Received performance entry `navigationInteractive` in clock.gaiamobile.org +123ms
  raptor:coldlaunch Received performance entry `visuallyLoaded` in clock.gaiamobile.org +245ms
  raptor:coldlaunch Received performance entry `contentInteractive` in clock.gaiamobile.org +3ms
  raptor:coldlaunch Received performance entry `fullyLoaded` in clock.gaiamobile.org +3ms
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb shell 'b2g-info | grep "Clock"' +1s
  mozdevice:logging Writing to log +223ms
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb shell 'log -p i -t PerformanceMemory "clock.gaiamobile.org|uss|11.4"' +0ms
  mozdevice:logging Writing to log +3ms
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb shell 'log -p i -t PerformanceMemory "clock.gaiamobile.org|pss|15.7"' +1ms
  mozdevice:logging Writing to log +3ms
  mozdevice:command [Executing] ANDROID_SERIAL=3739cec3 adb shell 'log -p i -t PerformanceMemory "clock.gaiamobile.org|rss|27.2"' +0ms
[Test] Run 1 timed out, retry attempt 1

**Comment by eliperelman** [comment]
@rwood-moz did you combine this with the Raptor patch?

**Comment by rwood-moz** [comment]
Nope but I will now!  Thought it was just changing the memory logging but makes sense raptor needs to look for the new tags... :/

**Comment by rwood-moz** [comment]
Much better ;)

**Comment by rwood-moz** [comment]
Works great on device but fails on emulator:

  raptor:coldlaunch Received performance entry `fullyLoaded` in settings.gaiamobile.org +2s
  mozdevice:command [Executing] ANDROID_SERIAL=emulator-5554 adb shell 'b2g-info | grep "Settings"' +21s
  mozdevice:logging Writing to log +1s
  mozdevice:command [Executing] ANDROID_SERIAL=emulator-5554 adb shell 'log -p i -t PerformanceMemory "settings.gaiamobile.org|uss|undefined"' +0ms
  mozdevice:logging Writing to log +2ms
  mozdevice:command [Executing] ANDROID_SERIAL=emulator-5554 adb shell 'log -p i -t PerformanceMemory "settings.gaiamobile.org|pss|undefined"' +0ms
  mozdevice:logging Writing to log +4ms
  mozdevice:command [Executing] ANDROID_SERIAL=emulator-5554 adb shell 'log -p i -t PerformanceMemory "settings.gaiamobile.org|rss|undefined"' +0ms
  raptor:coldlaunch Received PSS memory entry: NaNMB +1s
  raptor:coldlaunch Received RSS memory entry: NaNMB +16ms
  raptor:coldlaunch Received USS memory entry: NaNMB +7ms
[Test] Run 1 complete

b2g-info on emulator:

rwood@ubuntu:~$ adb shell b2g-info
                          |     megabytes     |
           NAME  PID PPID CPU(s) NICE  USS  PSS  RSS SWAP VSIZE OOM_ADJ USER  
            b2g 1765    1  117.5    0 47.1 53.6 71.0  0.0 183.4       0 root  
         (Nuwa) 1771 1765    3.1    0  3.9  8.5 23.2  0.0  64.3     -16 root  
Built-in Keyboa 1847 1771    2.9    0  7.6 10.7 23.4  0.0  76.7      10 app_1847
     Homescreen 1877 1765   31.7    0 16.4 22.0 36.3  0.0  94.3       8 app_1877
       Settings 2057 1771    5.5    0 14.2 18.0 32.1  0.0  90.3       2 app_2057
(Preallocated a 2118 1771    0.4    0  4.0  7.1 17.1  0.0  67.3       1 app_2118

System memory info:

```
        Total 503.9 MB
    SwapTotal   0.0 MB
 Used - cache 102.5 MB
```

  B2G procs (PSS) 119.9 MB
    Non-B2G procs -17.4 MB
     Free + cache 401.4 MB
             Free 285.9 MB
            Cache 115.4 MB
         SwapFree   0.0 MB

Low-memory killer parameters:

  notify_trigger -1 KB

  oom_adj min_free
        0  4096 KB
        1  5120 KB
        2  6144 KB
        6  7168 KB
        8  8192 KB
       10 20480 KB

b2g-info on actual flame:

rwood@ubuntu:~$ adb shell b2g-info
                     |     megabytes     |
      NAME  PID PPID CPU(s) NICE  USS  PSS  RSS SWAP VSIZE OOM_ADJ USER  
       b2g 3286    1   42.0    0 58.3 64.2 80.4  0.6 204.1       0 root  
    (Nuwa) 3299 3286    0.9    0  5.3  9.7 22.2  0.8  65.2     -16 root  
Homescreen 3450 3299    7.3    0  9.0 13.8 26.7  0.7  75.0       8 u0_a3450
  Settings 3669 3299    2.6    0 13.3 17.8 30.1  0.7  91.9       2 u0_a3669

System memory info:

```
        Total 215.3 MB
    SwapTotal 192.0 MB
 Used - cache 141.3 MB
```

  B2G procs (PSS) 105.5 MB
    Non-B2G procs  35.8 MB
     Free + cache  74.0 MB
             Free   3.3 MB
            Cache  70.7 MB
         SwapFree 180.8 MB

Low-memory killer parameters:

  notify_trigger 9216 KB

  oom_adj min_free
        0  4096 KB
       58  5120 KB
      117  6144 KB
      352  7168 KB
      470  8192 KB
      588 10240 KB

**Comment by eliperelman** [comment]
What is the output of `ANDROID_SERIAL=emulator-5554 adb shell 'b2g-info | grep "Settings"'`?

**Comment by rwood-moz** [comment]
rwood@ubuntu:~/gaia$ ANDROID_SERIAL=emulator-5554 adb shell 'b2g-info | grep "Settings"'
/system/bin/sh: grep: not found

haha... no grep on the emulator... this works instead:

rwood@ubuntu:~/gaia$ ANDROID_SERIAL=emulator-5554 adb shell 'b2g-info' | grep "Settings"       Settings 395  263   12.1    0 17.5 21.2 35.5  0.0  91.9       2 app_395

**Comment by eliperelman** [comment]
Oh haha.

Hmm, what if you change the `.memory` method to look like this:

``` js
Logging.prototype.memory = function(processName, application) {
  var logging = this;

  return new Command()
    .env('ANDROID_SERIAL', this.serial)
    .adbShell('b2g-info')
    .pipe('grep "' + processName + '"')
    .then(function(output) {
      var parts = output.split(/\s+/g);

      logging.info('PerformanceMemory', application + '|uss|' + parts[6]);
      logging.info('PerformanceMemory', application + '|pss|' + parts[7]);
      logging.info('PerformanceMemory', application + '|rss|' + parts[8]);
    });
};
```

**Comment by rwood-moz** [comment]
No that hangs:

  raptor:coldlaunch Capturing application PID: 5936 +1ms
  raptor:coldlaunch Received performance entry `navigationInteractive` in clock.gaiamobile.org +611ms
  raptor:coldlaunch Received performance entry `visuallyLoaded` in clock.gaiamobile.org +871ms
  raptor:coldlaunch Received performance entry `contentInteractive` in clock.gaiamobile.org +4ms
  raptor:coldlaunch Received performance entry `fullyLoaded` in clock.gaiamobile.org +6ms

I tried different things including this but didn't fix it.

```
  ...
  logging.info('PerformanceMemory', application + '|rss|' + parts[8]);
})
.exec();
```

};

**Comment by eliperelman** [comment]
Oh shoot, I forgot the `.exec`.

``` js
Logging.prototype.memory = function(processName, application) {
  var logging = this;

  return new Command()
    .env('ANDROID_SERIAL', this.serial)
    .adbShell('b2g-info')
    .pipe('grep "' + processName + '"')
    .exec()
    .then(function(output) {
      var parts = output.split(/\s+/g);

      logging.info('PerformanceMemory', application + '|uss|' + parts[6]);
      logging.info('PerformanceMemory', application + '|pss|' + parts[7]);
      logging.info('PerformanceMemory', application + '|rss|' + parts[8]);
    });
};
```

**Comment by rwood-moz** [comment]
Ah I put the exec() in the wrong place, ok cool yeasir that works.

**Pull request merged**
